# Generated by Django 2.1.2 on 2018-10-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carddet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnum', models.CharField(max_length=128)),
                ('pin', models.CharField(max_length=4)),
                ('balance', models.CharField(max_length=16)),
            ],
        ),
    ]
