# Generated by Django 2.1.2 on 2018-10-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddet',
            name='balance',
            field=models.CharField(default=0, max_length=16),
        ),
    ]
