# Generated by Django 2.1.2 on 2018-10-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20181020_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddet',
            name='pin',
            field=models.CharField(max_length=256),
        ),
    ]
